// Tool to generate Terraform HCL configuration for existing correlation rules.
//
// Usage:
//
//	go run ./tools/generate-correlation-rules
//
// This generates two files:
//   - correlation_rules.tf: HCL resource definitions
//   - import_correlation_rules.sh: Bash script with terraform import commands
//
// Required environment variables:
//   - FALCON_CLIENT_ID
//   - FALCON_CLIENT_SECRET
//   - FALCON_CLOUD (optional, defaults to autodiscover)
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
	"text/template"
	"time"

	"github.com/crowdstrike/gofalcon/falcon"
	"github.com/crowdstrike/gofalcon/falcon/client"
	"github.com/crowdstrike/gofalcon/falcon/client/correlation_rules"
	"github.com/crowdstrike/gofalcon/falcon/models"
)

const hclTemplate = `resource "crowdstrike_correlation_rule" "{{.ResourceName}}" {
  name              = {{quote .Rule.Name}}
  customer_id       = {{quote .Rule.CustomerID}}
{{- if .Rule.Description}}
  description       = {{quote .Rule.Description}}
{{- end}}
  severity          = {{.Rule.Severity}}
  status            = {{quote .Rule.Status}}
  trigger_on_create = false
{{- if .Rule.Comment}}
  comment           = {{quote .Rule.Comment}}
{{- end}}

  search {
    filter       = {{quote .Rule.Search.Filter}}
    lookback     = {{quote .Rule.Search.Lookback}}
    outcome      = {{quote .Rule.Search.Outcome}}
    trigger_mode = {{quote .Rule.Search.TriggerMode}}
{{- if ne .Rule.Search.ExecutionMode "scheduled"}}
    execution_mode = {{quote .Rule.Search.ExecutionMode}}
{{- end}}
{{- if .Rule.Search.UseIngestTime}}
    use_ingest_time = {{.Rule.Search.UseIngestTime}}
{{- end}}
{{- if .Rule.Search.CaseTemplateID}}
    case_template_id = {{quote .Rule.Search.CaseTemplateID}}
{{- end}}
  }
{{- if .Rule.Operation.HasContent}}

  operation {
{{- if .Rule.Operation.Schedule}}
    schedule {
      definition = {{quote .Rule.Operation.Schedule.Definition}}
    }
{{- end}}
{{- if .Rule.Operation.StartOn}}
    start_on = {{quote .Rule.Operation.StartOn}}
{{- end}}
{{- if .Rule.Operation.StopOn}}
    stop_on = {{quote .Rule.Operation.StopOn}}
{{- end}}
  }
{{- end}}
{{range .Rule.MitreAttack}}
  mitre_attack {
    tactic_id    = {{quote .TacticID}}
{{- if .TechniqueID}}
    technique_id = {{quote .TechniqueID}}
{{- end}}
  }
{{- end}}
{{- range .Rule.Notifications}}
  notification {
    type = {{quote .Type}}
{{- if .Options}}
    options = {
{{- range $k, $v := .Options}}
      {{quote $k}} = {{quote $v}}
{{- end}}
    }
{{- end}}
    config {
      cid        = {{quote .Config.Cid}}
{{- if .Config.ConfigID}}
      config_id  = {{quote .Config.ConfigID}}
{{- end}}
{{- if .Config.PluginID}}
      plugin_id  = {{quote .Config.PluginID}}
{{- end}}
{{- if .Config.Recipients}}
      recipients = [{{range $i, $r := .Config.Recipients}}{{if $i}}, {{end}}{{quote $r}}{{end}}]
{{- end}}
{{- if .Config.Severity}}
      severity   = {{quote .Config.Severity}}
{{- end}}
    }
  }
{{- end}}
{{- range .Rule.GuardrailNotifications}}
  guardrail_notification {
    type = {{quote .Type}}
{{- if .Options}}
    options = {
{{- range $k, $v := .Options}}
      {{quote $k}} = {{quote $v}}
{{- end}}
    }
{{- end}}
    config {
      cid        = {{quote .Config.Cid}}
{{- if .Config.ConfigID}}
      config_id  = {{quote .Config.ConfigID}}
{{- end}}
{{- if .Config.PluginID}}
      plugin_id  = {{quote .Config.PluginID}}
{{- end}}
{{- if .Config.Recipients}}
      recipients = [{{range $i, $r := .Config.Recipients}}{{if $i}}, {{end}}{{quote $r}}{{end}}]
{{- end}}
{{- if .Config.Severity}}
      severity   = {{quote .Config.Severity}}
{{- end}}
    }
  }
{{- end}}
}
`

const importScriptHeader = `#!/bin/bash
# Terraform import script for correlation rules
# Generated by: go run ./tools/generate-correlation-rules
#
# Usage: ./import_correlation_rules.sh
#
# Make sure to run 'terraform init' first and have the correlation_rules.tf file in place.

set -e

`

// heredocSentinel is the delimiter used for HCL heredoc strings.  Chosen to be
// unlikely to appear in CQL filter queries.
const heredocSentinel = "CROWDSTRIKE_HEREDOC"

var resourceNameRegexp = regexp.MustCompile(`[^a-z0-9]+`)

type ruleData struct {
	ResourceName string
	Rule         *ruleView
}

// ruleView is a simplified view of the rule for templating
type ruleView struct {
	ID                     string
	Name                   string
	CustomerID             string
	Description            string
	Severity               int32
	Status                 string
	Comment                string
	Search                 *searchView
	Operation              *operationView
	MitreAttack            []*mitreAttackView
	Notifications          []*notificationView
	GuardrailNotifications []*notificationView
}

type searchView struct {
	Filter         string
	Lookback       string
	Outcome        string
	TriggerMode    string
	ExecutionMode  string
	UseIngestTime  bool
	CaseTemplateID string
}

type operationView struct {
	Schedule *scheduleView
	StartOn  string
	StopOn   string
}

// HasContent returns true if the operation block has any fields to render.
func (o *operationView) HasContent() bool {
	return o.Schedule != nil || o.StartOn != "" || o.StopOn != ""
}

type scheduleView struct {
	Definition string
}

type mitreAttackView struct {
	TacticID    string
	TechniqueID string
}

type notificationView struct {
	Type    string
	Options map[string]string
	Config  *notificationConfigView
}

type notificationConfigView struct {
	Cid        string
	ConfigID   string
	PluginID   string
	Recipients []string
	Severity   string
}

func main() {
	ctx := context.Background()

	clientID := os.Getenv("FALCON_CLIENT_ID")
	clientSecret := os.Getenv("FALCON_CLIENT_SECRET")
	cloud := os.Getenv("FALCON_CLOUD")

	if clientID == "" || clientSecret == "" {
		log.Fatal("FALCON_CLIENT_ID and FALCON_CLIENT_SECRET environment variables are required")
	}

	if cloud == "" {
		cloud = "autodiscover"
	}

	falconCloud, err := falcon.CloudValidate(cloud)
	if err != nil {
		log.Fatalf("Invalid FALCON_CLOUD: %v", err)
	}

	apiClient, err := falcon.NewClient(&falcon.ApiConfig{
		ClientId:     clientID,
		ClientSecret: clientSecret,
		Cloud:        falconCloud,
		Context:      ctx,
	})
	if err != nil {
		log.Fatalf("Failed to create API client: %v", err)
	}

	rules, err := fetchAllRules(ctx, apiClient)
	if err != nil {
		log.Fatalf("Failed to fetch rules: %v", err)
	}

	fmt.Fprintf(os.Stderr, "Found %d correlation rules\n", len(rules))

	if err := generateFiles(rules); err != nil {
		log.Fatalf("Failed to generate files: %v", err)
	}
}

func fetchAllRules(ctx context.Context, apiClient *client.CrowdStrikeAPISpecification) ([]*models.CorrelationrulesapiRuleV1, error) {
	var allRules []*models.CorrelationrulesapiRuleV1
	var offset int64 = 0
	limit := int64(100)

	for {
		resp, err := apiClient.CorrelationRules.CombinedRulesGetV1(&correlation_rules.CombinedRulesGetV1Params{
			Context: ctx,
			Offset:  &offset,
			Limit:   &limit,
		})
		if err != nil {
			return nil, fmt.Errorf("API call failed: %w", err)
		}

		if resp.Payload == nil || len(resp.Payload.Resources) == 0 {
			break
		}

		allRules = append(allRules, resp.Payload.Resources...)

		if len(resp.Payload.Resources) < int(limit) {
			break
		}
		offset += limit
	}

	return allRules, nil
}

func generateFiles(rules []*models.CorrelationrulesapiRuleV1) error {
	funcMap := template.FuncMap{
		"quote": quoteHCL,
	}

	tpl, err := template.New("hcl").Funcs(funcMap).Parse(hclTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Create HCL file
	hclFile, err := os.Create("correlation_rules.tf")
	if err != nil {
		return fmt.Errorf("failed to create correlation_rules.tf: %w", err)
	}
	defer hclFile.Close()

	// Create import script
	importFile, err := os.Create("import_correlation_rules.sh")
	if err != nil {
		return fmt.Errorf("failed to create import_correlation_rules.sh: %w", err)
	}
	defer importFile.Close()

	// Make import script executable
	if err := importFile.Chmod(0755); err != nil {
		return fmt.Errorf("failed to make import script executable: %w", err)
	}

	// Write import script header
	if _, err := importFile.WriteString(importScriptHeader); err != nil {
		return fmt.Errorf("failed to write import script header: %w", err)
	}

	seenNames := make(map[string]int)

	for _, rule := range rules {
		resourceName := uniqueResourceName(rule.Name, seenNames)
		data := ruleData{
			ResourceName: resourceName,
			Rule:         toRuleView(rule),
		}

		ruleID := "<unknown>"
		if rule.ID != nil {
			ruleID = *rule.ID
		}

		// Write HCL resource
		if err := tpl.Execute(hclFile, data); err != nil {
			return fmt.Errorf("failed to execute template for rule %s: %w", ruleID, err)
		}
		if _, err := hclFile.WriteString("\n"); err != nil {
			return fmt.Errorf("failed to write newline: %w", err)
		}

		// Write import command
		importCmd := fmt.Sprintf("terraform import crowdstrike_correlation_rule.%s %s\n",
			resourceName, ruleID)
		if _, err := importFile.WriteString(importCmd); err != nil {
			return fmt.Errorf("failed to write import command: %w", err)
		}
	}

	fmt.Fprintf(os.Stderr, "Generated: correlation_rules.tf\n")
	fmt.Fprintf(os.Stderr, "Generated: import_correlation_rules.sh\n")

	return nil
}

// quoteHCL formats a value for use in HCL. Multiline strings use heredoc
// syntax (literal, no escape processing). Single-line strings use quoted
// syntax with backslash and quote escaping.
func quoteHCL(s any) string {
	var str string
	switch v := s.(type) {
	case string:
		str = v
	case *string:
		if v == nil {
			return `""`
		}
		str = *v
	default:
		return `""`
	}

	// Multiline → heredoc (literal, no escaping needed)
	if strings.Contains(str, "\n") {
		str = strings.TrimRight(str, "\n")
		return fmt.Sprintf("<<%s\n%s\n%s", heredocSentinel, str, heredocSentinel)
	}

	// Single-line → quoted string (must escape backslashes and quotes)
	str = strings.ReplaceAll(str, `\`, `\\`)
	str = strings.ReplaceAll(str, `"`, `\"`)
	return fmt.Sprintf(`"%s"`, str)
}

// uniqueResourceName converts a rule name to a valid Terraform resource name
// and appends a numeric suffix on collision.
func uniqueResourceName(name *string, seen map[string]int) string {
	base := toResourceName(name)

	count := seen[base]
	seen[base] = count + 1

	if count == 0 {
		return base
	}
	return fmt.Sprintf("%s_%d", base, count)
}

func toResourceName(name *string) string {
	if name == nil {
		return "unnamed"
	}

	// Convert to lowercase and replace non-alphanumeric with underscores
	s := strings.ToLower(*name)
	s = resourceNameRegexp.ReplaceAllString(s, "_")

	// Remove leading/trailing underscores
	s = strings.Trim(s, "_")

	// Ensure it starts with a letter
	if len(s) > 0 && (s[0] >= '0' && s[0] <= '9') {
		s = "rule_" + s
	}

	if s == "" {
		s = "unnamed"
	}

	return s
}

func toRuleView(rule *models.CorrelationrulesapiRuleV1) *ruleView {
	view := &ruleView{
		Description: rule.Description,
		Comment:     rule.Comment,
		Operation:   &operationView{}, // always initialized to avoid nil panics in template
	}

	if rule.ID != nil {
		view.ID = *rule.ID
	}
	if rule.Name != nil {
		view.Name = *rule.Name
	}
	if rule.CustomerID != nil {
		view.CustomerID = *rule.CustomerID
	}
	if rule.Severity != nil {
		view.Severity = *rule.Severity
	}
	if rule.Status != nil {
		view.Status = *rule.Status
	}

	if rule.Search != nil {
		view.Search = &searchView{
			CaseTemplateID: rule.Search.CaseTemplateID,
			ExecutionMode:  "scheduled", // default
		}
		if rule.Search.Filter != nil {
			view.Search.Filter = *rule.Search.Filter
		}
		if rule.Search.Lookback != nil {
			view.Search.Lookback = *rule.Search.Lookback
		}
		if rule.Search.Outcome != nil {
			view.Search.Outcome = *rule.Search.Outcome
		}
		if rule.Search.TriggerMode != nil {
			view.Search.TriggerMode = *rule.Search.TriggerMode
		} else {
			view.Search.TriggerMode = "verbose" // safe default when API omits it
		}
		if rule.Search.ExecutionMode != nil {
			view.Search.ExecutionMode = *rule.Search.ExecutionMode
		}
		if rule.Search.UseIngestTime != nil {
			view.Search.UseIngestTime = *rule.Search.UseIngestTime
		}
	}

	if rule.Operation != nil {
		if rule.Operation.Schedule != nil && rule.Operation.Schedule.Definition != nil {
			view.Operation.Schedule = &scheduleView{
				Definition: *rule.Operation.Schedule.Definition,
			}
		}
		if !rule.Operation.StartOn.IsZero() {
			view.Operation.StartOn = time.Time(rule.Operation.StartOn).Format(time.RFC3339)
		}
		if !rule.Operation.StopOn.IsZero() {
			view.Operation.StopOn = time.Time(rule.Operation.StopOn).Format(time.RFC3339)
		}
	}

	for _, m := range rule.MitreAttack {
		if m == nil {
			continue
		}
		ma := &mitreAttackView{
			TechniqueID: m.TechniqueID,
		}
		if m.TacticID != nil {
			ma.TacticID = *m.TacticID
		}
		view.MitreAttack = append(view.MitreAttack, ma)
	}

	view.Notifications = toNotificationViews(rule.Notifications)
	view.GuardrailNotifications = toNotificationViews(rule.GuardrailNotifications)

	return view
}

func toNotificationViews(notifications []*models.CorrelationrulesapiRuleNotificationsV1) []*notificationView {
	var views []*notificationView
	for _, n := range notifications {
		if n == nil {
			continue
		}
		nv := &notificationView{
			Options: n.Options,
		}
		if n.Type != nil {
			nv.Type = *n.Type
		}
		if n.Config != nil {
			nv.Config = &notificationConfigView{}
			if n.Config.Cid != nil {
				nv.Config.Cid = *n.Config.Cid
			}
			if n.Config.ConfigID != nil {
				nv.Config.ConfigID = *n.Config.ConfigID
			}
			if n.Config.PluginID != nil {
				nv.Config.PluginID = *n.Config.PluginID
			}
			if n.Config.Severity != nil {
				nv.Config.Severity = *n.Config.Severity
			}
			nv.Config.Recipients = n.Config.Recipients
		}
		views = append(views, nv)
	}
	return views
}
